### ISSUE TITLE
涉及到python-qrcode这个包，就会报错。

### ISSUE THREAD

**Issue by oxsard** [emacs-eaf/eaf-airshare#1]
Traceback (most recent call last):
  File "/home/oxsard/.emacs.d.28.1/site-lisp/emacs-application-framework/core/utils.py", line 55, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 173, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/app/airshare/buffer.py", line 35, in __init__
    self.add_widget(AirShareWidget(url, self.theme_foreground_color))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/app/airshare/buffer.py", line 100, in __init__
    self.qrcode_label.setPixmap(qrcode.make(url, image_factory=Image).pixmap())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/main.py", line 29, in make
    return qr.make_image()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/main.py", line 365, in make_image
    im = image_factory(
         ^^^^^^^^^^^^^^
TypeError: Image.__init__() got an unexpected keyword argument 'qrcode_modules'
Traceback (most recent call last):
  File "/home/oxsard/.emacs.d.28.1/site-lisp/emacs-application-framework/core/utils.py", line 55, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 173, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/app/airshare/buffer.py", line 35, in __init__
    self.add_widget(AirShareWidget(url, self.theme_foreground_color))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/app/airshare/buffer.py", line 100, in __init__
    self.qrcode_label.setPixmap(qrcode.make(url, image_factory=Image).pixmap())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/main.py", line 29, in make
    return qr.make_image()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/main.py", line 365, in make_image
    im = image_factory(
         ^^^^^^^^^^^^^^
TypeError: Image.__init__() got an unexpected keyword argument 'qrcode_modules'
Traceback (most recent call last):
  File "/home/oxsard/.emacs.d.28.1/site-lisp/emacs-application-framework/core/utils.py", line 55, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 170, in create_buffer
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/app/file-manager/buffer.py'
Traceback (most recent call last):
  File "/home/oxsard/.emacs.d.28.1/site-lisp/emacs-application-framework/core/utils.py", line 55, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 170, in create_buffer
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] 没有那个文件或目录: '/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/app/file-manager/buffer.py'
Traceback (most recent call last):
  File "/home/oxsard/.emacs.d.28.1/site-lisp/emacs-application-framework/core/utils.py", line 55, in on_signal_received
    self._func(obj, *args, **kwargs)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 155, in new_buffer
    self.create_buffer(buffer_id, url, module_path, arguments)
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 173, in create_buffer
    app_buffer = module.AppBuffer(buffer_id, url, arguments)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/app/file-browser/buffer.py", line 42, in __init__
    self.add_widget(FileUploaderWidget(url, self.theme_background_color, self.theme_foreground_color))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oxsard/.emacs.d/site-lisp/emacs-application-framework/app/file-browser/buffer.py", line 121, in __init__
    self.qrcode_label.setPixmap(qrcode.make(self.address, image_factory=Image).pixmap())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/main.py", line 29, in make
    return qr.make_image()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrcode/main.py", line 365, in make_image
    im = image_factory(
         ^^^^^^^^^^^^^^
TypeError: Image.__init__() got an unexpected keyword argument 'qrcode_modules'

**Comment by manateelazycat** [comment]
给一下重现步骤

**Comment by manateelazycat** [comment]
你就没有安装依赖啊

**Comment by oxsard** [comment]
不是的，archlinux的extra/python-qrcode已经安装的，我也不明白为啥会报unexpected argument
'qrcode_moduled'这个错误

Andy Stewart ***@***.***>于2023年7月9日 周日08:46写道：

**Comment by manateelazycat** [comment]
怎么安装的，重现步骤是啥？

**Comment by oxsard** [comment]
其他用户没有这个情况是么？奇怪。。

全新克隆的eaf目录，在archlinux，确保没有pip的包进来，逐个安装依赖，有几个包是只有aur里面有的，分别正常安装，确保python-qrcode顺利安装。
然后用emacs -Q启动，按照顺序require eaf和airshare两个包

其他几个大部件没啥问题，就这几个分享相关的会用到二维码，会导致如上TypeError

Andy Stewart ***@***.***>于2023年7月9日 周日13:02写道：

**Comment by manateelazycat** [comment]
为啥不用install-eaf.py 脚本安装？

**Comment by oxsard** [comment]
你好，是这样的，我是按照说明用install-eaf.py安装的，但是有几个包是安不了的，包括不限于sexpdata，epc，pymupdf(这个不知道为啥没安装上，按理来说没问题的)，playsound等等，只能在aur找到，我是用yay安装的。

Andy Stewart ***@***.***>于2023年7月9日 周日16:11写道：

**Comment by manateelazycat** [comment]
应该是 python-qrcode 升级以后， API发生变化导致的

**Comment by manateelazycat** [comment]
所有用 python-qrcode 的EAF App都修复了。

**Comment by oxsard** [comment]
猫哥我能请你喝杯咖啡麽，请满足我这个要求。
Andy Stewart ***@***.***>于2023年7月11日 周二11:48写道：

**Comment by manateelazycat** [comment]
心领了，谢谢，你们开心就是对我最大的鼓励
